# Generated by Django 5.2.17 on 2026-08-12 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_leaderboard_rank'),
        ('orders', '0004_order_client_refusals'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='preferred_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_orders', to='masters.masterprofile'),
        ),
    ]
