# Generated by Django 5.2.17 on 2026-08-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_preferred_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('client_cancelled', 'Client cancelled'), ('master_declined', 'Master declined'), ('price_rejected', 'Price rejected'), ('master_no_response', 'Master no response'), ('no_master_found', 'No master found'), ('replaced_by_new_order', 'Replaced by a newer order'), ('system', 'System')], max_length=64),
        ),
    ]
