# Generated by Django 5.2.17 on 2026-09-14 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0008_alter_mastercategoryprice_options_and_more'),
        ('orders', '0006_alter_order_cancellation_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masteroffer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Предложение мастеру', 'verbose_name_plural': 'Предложения мастерам'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderattachment',
            options={'ordering': ['uploaded_at'], 'verbose_name': 'Вложение заказа', 'verbose_name_plural': 'Вложения заказов'},
        ),
        migrations.AlterModelOptions(
            name='orderevent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Событие заказа', 'verbose_name_plural': 'События заказов'},
        ),
        migrations.AlterModelOptions(
            name='priceproposal',
            options={'ordering': ['-created_at'], 'verbose_name': 'Предложение цены', 'verbose_name_plural': 'Предложения цены'},
        ),
        migrations.AlterField(
            model_name='masteroffer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='masteroffer',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Истекает'),
        ),
        migrations.AlterField(
            model_name='masteroffer',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_offers', to='masters.masterprofile', verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='masteroffer',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_offers', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='masteroffer',
            name='radius_km',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Радиус, км'),
        ),
        migrations.AlterField(
            model_name='masteroffer',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ответ получен'),
        ),
        migrations.AlterField(
            model_name='masteroffer',
            name='score',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Скор'),
        ),
        migrations.AlterField(
            model_name='masteroffer',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принято'), ('declined', 'Отклонено'), ('expired', 'Истекло')], default='pending', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_text',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='agreed_price_uzs',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Согласованная цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='budget_ceiling_uzs',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Бюджет клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cancellation_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий к отмене'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('client_cancelled', 'Отменил клиент'), ('master_declined', 'Отказал мастер'), ('price_rejected', 'Цена отклонена'), ('master_no_response', 'Мастер не ответил'), ('no_master_found', 'Мастер не найден'), ('replaced_by_new_order', 'Заменён новым заказом'), ('system', 'Системная отмена')], max_length=64, verbose_name='Причина отмены'),
        ),
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='masters.servicecategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_orders', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_refusals',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Отказов клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершён'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='order',
            name='final_price_uzs',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Итоговая цена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='order',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='masters.masterprofile', verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='needs_operator',
            field=models.BooleanField(default=False, verbose_name='Нужен оператор'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, max_length=32, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='preferred_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_orders', to='masters.masterprofile', verbose_name='Выбранный мастер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_flexible',
            field=models.BooleanField(default=False, verbose_name='Цена гибкая'),
        ),
        migrations.AlterField(
            model_name='order',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Запланировано на'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('searching', 'Идёт поиск'), ('offered_to_master', 'Предложен мастеру'), ('accepted_by_master', 'Принят мастером'), ('price_proposed', 'Предложена цена'), ('price_accepted', 'Цена согласована'), ('master_on_way', 'Мастер в пути'), ('master_arrived', 'Мастер на месте'), ('in_progress', 'В работе'), ('work_done', 'Работа выполнена'), ('completed', 'Завершён'), ('cancelled', 'Отменён'), ('expired', 'Истёк'), ('disputed', 'Спорный')], default='draft', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='orderattachment',
            name='file',
            field=models.ImageField(upload_to='orders/%Y/%m/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='orderattachment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='orderattachment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Загружен'),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Инициатор'),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='from_status',
            field=models.CharField(blank=True, max_length=32, verbose_name='Из статуса'),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Доп. данные'),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='reason',
            field=models.CharField(blank=True, max_length=120, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='to_status',
            field=models.CharField(max_length=32, verbose_name='В статус'),
        ),
        migrations.AlterField(
            model_name='priceproposal',
            name='amount_uzs',
            field=models.PositiveIntegerField(verbose_name='Сумма, UZS'),
        ),
        migrations.AlterField(
            model_name='priceproposal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='priceproposal',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_proposals', to='masters.masterprofile', verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='priceproposal',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_proposals', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='priceproposal',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ответ получен'),
        ),
        migrations.AlterField(
            model_name='priceproposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принято'), ('rejected', 'Отклонено'), ('withdrawn', 'Отозвано')], default='pending', max_length=32, verbose_name='Статус'),
        ),
    ]
