# Generated by Django 5.2.17 on 2026-09-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar_user_birth_date_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='myid_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pinfl',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
