# Generated by Django 5.2.17 on 2026-09-14 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_subscription_reminder_marker'),
        ('masters', '0008_alter_mastercategoryprice_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterledgerentry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Операция кошелька', 'verbose_name_plural': 'Операции кошельков'},
        ),
        migrations.AlterModelOptions(
            name='mastersubscription',
            options={'verbose_name': 'Подписка мастера', 'verbose_name_plural': 'Подписки мастеров'},
        ),
        migrations.AlterModelOptions(
            name='masterwallet',
            options={'verbose_name': 'Кошелёк мастера', 'verbose_name_plural': 'Кошельки мастеров'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['sort_order', 'orders_count'], 'verbose_name': 'Пакет', 'verbose_name_plural': 'Пакеты'},
        ),
        migrations.AlterModelOptions(
            name='packagepurchase',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка на пакет', 'verbose_name_plural': 'Заявки на пакеты'},
        ),
        migrations.AlterField(
            model_name='masterledgerentry',
            name='amount_uzs',
            field=models.IntegerField(verbose_name='Сумма, UZS'),
        ),
        migrations.AlterField(
            model_name='masterledgerentry',
            name='balance_after_uzs',
            field=models.IntegerField(verbose_name='Баланс после'),
        ),
        migrations.AlterField(
            model_name='masterledgerentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='masterledgerentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ledger_entries', to=settings.AUTH_USER_MODEL, verbose_name='Кем создана'),
        ),
        migrations.AlterField(
            model_name='masterledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('manual_top_up', 'Ручное пополнение'), ('package_purchase', 'Покупка пакета'), ('order_debit', 'Списание за заказ'), ('adjustment', 'Корректировка')], max_length=32, verbose_name='Тип операции'),
        ),
        migrations.AlterField(
            model_name='masterledgerentry',
            name='note',
            field=models.TextField(blank=True, verbose_name='Заметка'),
        ),
        migrations.AlterField(
            model_name='masterledgerentry',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='billing.masterwallet', verbose_name='Кошелёк'),
        ),
        migrations.AlterField(
            model_name='mastersubscription',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Активирована'),
        ),
        migrations.AlterField(
            model_name='mastersubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='mastersubscription',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Истекает'),
        ),
        migrations.AlterField(
            model_name='mastersubscription',
            name='frozen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Заморожена с'),
        ),
        migrations.AlterField(
            model_name='mastersubscription',
            name='is_frozen',
            field=models.BooleanField(default=False, verbose_name='Заморожена'),
        ),
        migrations.AlterField(
            model_name='mastersubscription',
            name='master',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='masters.masterprofile', verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='mastersubscription',
            name='orders_remaining',
            field=models.PositiveIntegerField(default=0, verbose_name='Осталось заказов'),
        ),
        migrations.AlterField(
            model_name='mastersubscription',
            name='reminder_marker',
            field=models.CharField(blank=True, max_length=8, verbose_name='Метка напоминания'),
        ),
        migrations.AlterField(
            model_name='mastersubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлена'),
        ),
        migrations.AlterField(
            model_name='masterwallet',
            name='balance_uzs',
            field=models.PositiveIntegerField(default=0, verbose_name='Баланс, UZS'),
        ),
        migrations.AlterField(
            model_name='masterwallet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='masterwallet',
            name='free_orders_remaining',
            field=models.PositiveIntegerField(default=10, verbose_name='Бесплатных заказов'),
        ),
        migrations.AlterField(
            model_name='masterwallet',
            name='master',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='masters.masterprofile', verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='masterwallet',
            name='package_orders_remaining',
            field=models.PositiveIntegerField(default=0, verbose_name='Заказов по пакету'),
        ),
        migrations.AlterField(
            model_name='masterwallet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='package',
            name='name_ru',
            field=models.CharField(max_length=120, verbose_name='Название (рус)'),
        ),
        migrations.AlterField(
            model_name='package',
            name='name_uz',
            field=models.CharField(max_length=120, verbose_name='Название (узб)'),
        ),
        migrations.AlterField(
            model_name='package',
            name='orders_count',
            field=models.PositiveIntegerField(verbose_name='Кол-во заказов'),
        ),
        migrations.AlterField(
            model_name='package',
            name='price_uzs',
            field=models.PositiveIntegerField(verbose_name='Цена, UZS'),
        ),
        migrations.AlterField(
            model_name='package',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='package',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='packagepurchase',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Активирована'),
        ),
        migrations.AlterField(
            model_name='packagepurchase',
            name='activated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_package_purchases', to=settings.AUTH_USER_MODEL, verbose_name='Активировал'),
        ),
        migrations.AlterField(
            model_name='packagepurchase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='packagepurchase',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='Бесплатно'),
        ),
        migrations.AlterField(
            model_name='packagepurchase',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_purchases', to='masters.masterprofile', verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='packagepurchase',
            name='note',
            field=models.TextField(blank=True, verbose_name='Заметка'),
        ),
        migrations.AlterField(
            model_name='packagepurchase',
            name='orders_count',
            field=models.PositiveIntegerField(verbose_name='Кол-во заказов'),
        ),
        migrations.AlterField(
            model_name='packagepurchase',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='billing.package', verbose_name='Пакет'),
        ),
        migrations.AlterField(
            model_name='packagepurchase',
            name='price_uzs',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена, UZS'),
        ),
        migrations.AlterField(
            model_name='packagepurchase',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('activated', 'Активирован'), ('rejected', 'Отклонён')], default='pending', max_length=16, verbose_name='Статус'),
        ),
    ]
