# Generated by Django 5.2.17 on 2026-09-14 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_masterprofile_online_since'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mastercategoryprice',
            options={'ordering': ['category__sort_order'], 'verbose_name': 'Услуга мастера', 'verbose_name_plural': 'Услуги мастеров'},
        ),
        migrations.AlterModelOptions(
            name='masterprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Мастер', 'verbose_name_plural': 'Мастера'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['sort_order', 'name_ru'], 'verbose_name': 'Категория услуг', 'verbose_name_plural': 'Категории услуг'},
        ),
        migrations.AlterField(
            model_name='mastercategoryprice',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='master_prices', to='masters.servicecategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='mastercategoryprice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='mastercategoryprice',
            name='experience_years',
            field=models.CharField(blank=True, max_length=16, verbose_name='Опыт (лет)'),
        ),
        migrations.AlterField(
            model_name='mastercategoryprice',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='mastercategoryprice',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_prices', to='masters.masterprofile', verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='mastercategoryprice',
            name='max_price_uzs',
            field=models.PositiveIntegerField(verbose_name='Цена до'),
        ),
        migrations.AlterField(
            model_name='mastercategoryprice',
            name='min_price_uzs',
            field=models.PositiveIntegerField(verbose_name='Цена от'),
        ),
        migrations.AlterField(
            model_name='mastercategoryprice',
            name='reject_reason',
            field=models.TextField(blank=True, verbose_name='Причина отказа'),
        ),
        migrations.AlterField(
            model_name='mastercategoryprice',
            name='status',
            field=models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Подтверждена'), ('rejected', 'Отклонена')], default='approved', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='masterprofile',
            name='activity_points',
            field=models.IntegerField(default=400, verbose_name='Баллы активности'),
        ),
        migrations.AlterField(
            model_name='masterprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Подтверждён'),
        ),
        migrations.AlterField(
            model_name='masterprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='masterprofile',
            name='block_reason',
            field=models.TextField(blank=True, verbose_name='Причина блокировки'),
        ),
        migrations.AlterField(
            model_name='masterprofile',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Заблокирован'),
        ),
        migrations.AlterField(
            model_name='masterprofile',
            name='completed_orders_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Выполнено заказов'),
        ),
        migrations.AlterField(
            model_name='masterprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='masterprofile',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='masterprofile',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='masterprofile',
            name='face_photo_url',
            field=models.URLField(blank=True, verbose_name='Фото лица'),
        ),
        migrations.AlterField(
            model_name='masterprofile',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='На линии'),
        ),
        migrations.AlterField(
            model_name='masterprofile',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность'),
        ),
        migrations.AlterField(
            model_name='masterprofile',
            name='leaderboard_rank',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Место в рейтинге'),
        ),
        migrations.AlterField(
            model_name='masterprofile',
            name='leaderboard_rank_prev',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Прошлое место'),
        ),
        migrations.AlterField(
            model_name='masterprofile',
            name='online_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='На линии с'),
        ),
        migrations.AlterField(
            model_name='masterprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='masterprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Подтверждён'), ('rejected', 'Отклонён'), ('blocked', 'Заблокирован')], default='pending', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='masterprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='masterprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='color_hex',
            field=models.CharField(blank=True, max_length=16, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='icon',
            field=models.CharField(blank=True, max_length=16, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name_ru',
            field=models.CharField(max_length=120, verbose_name='Название (рус)'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name_uz',
            field=models.CharField(max_length=120, verbose_name='Название (узб)'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Порядок'),
        ),
    ]
