# Generated by Django 5.2.17 on 2026-09-14 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_masteroffer_options_alter_order_options_and_more'),
        ('support', '0002_supportcase_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportcase',
            options={'ordering': ['-created_at'], 'verbose_name': 'Обращение в поддержку', 'verbose_name_plural': 'Обращения в поддержку'},
        ),
        migrations.AlterModelOptions(
            name='supportmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Сообщение поддержки', 'verbose_name_plural': 'Сообщения поддержки'},
        ),
        migrations.AlterField(
            model_name='supportcase',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_cases', to=settings.AUTH_USER_MODEL, verbose_name='Назначено'),
        ),
        migrations.AlterField(
            model_name='supportcase',
            name='body',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='supportcase',
            name='close_reason',
            field=models.CharField(blank=True, max_length=64, verbose_name='Причина закрытия'),
        ),
        migrations.AlterField(
            model_name='supportcase',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Закрыто'),
        ),
        migrations.AlterField(
            model_name='supportcase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='supportcase',
            name='last_operator_message_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее сообщение оператора'),
        ),
        migrations.AlterField(
            model_name='supportcase',
            name='last_user_message_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее сообщение пользователя'),
        ),
        migrations.AlterField(
            model_name='supportcase',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_cases', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='supportcase',
            name='priority',
            field=models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='normal', max_length=32, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='supportcase',
            name='status',
            field=models.CharField(choices=[('open', 'Открыто'), ('in_progress', 'В работе'), ('resolved', 'Решено'), ('closed', 'Закрыто')], default='open', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='supportcase',
            name='subject',
            field=models.CharField(max_length=180, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='supportcase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='supportcase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_cases', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportcase', verbose_name='Обращение'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Отправлено'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='supportmessage',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
