# Generated by Django 5.2.17 on 2026-09-14 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_use_osm_provider_default'),
        ('masters', '0008_alter_mastercategoryprice_options_and_more'),
        ('orders', '0006_alter_order_cancellation_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geoproviderevent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Событие геосервиса', 'verbose_name_plural': 'События геосервиса'},
        ),
        migrations.AlterModelOptions(
            name='masterlocationping',
            options={'ordering': ['-created_at'], 'verbose_name': 'Координата мастера', 'verbose_name_plural': 'Координаты мастеров'},
        ),
        migrations.AlterField(
            model_name='geoproviderevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='geoproviderevent',
            name='event_type',
            field=models.CharField(max_length=80, verbose_name='Тип события'),
        ),
        migrations.AlterField(
            model_name='geoproviderevent',
            name='payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Доп. данные'),
        ),
        migrations.AlterField(
            model_name='geoproviderevent',
            name='provider',
            field=models.CharField(choices=[('osm', 'OpenStreetMap'), ('mock', 'Заглушка')], default='osm', max_length=32, verbose_name='Провайдер'),
        ),
        migrations.AlterField(
            model_name='masterlocationping',
            name='accuracy_meters',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Точность, м'),
        ),
        migrations.AlterField(
            model_name='masterlocationping',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='masterlocationping',
            name='heading_degrees',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Курс, °'),
        ),
        migrations.AlterField(
            model_name='masterlocationping',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='masterlocationping',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='masterlocationping',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to='masters.masterprofile', verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='masterlocationping',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_pings', to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='masterlocationping',
            name='speed_mps',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Скорость, м/с'),
        ),
    ]
