# Generated by Django 5.2.17 on 2026-09-14 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_devicetoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicetoken',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Токен устройства', 'verbose_name_plural': 'Токены устройств'},
        ),
        migrations.AlterModelOptions(
            name='notificationevent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='platform',
            field=models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='android', max_length=16, verbose_name='Платформа'),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='token',
            field=models.CharField(max_length=255, unique=True, verbose_name='Токен'),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='notificationevent',
            name='body',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='notificationevent',
            name='channel',
            field=models.CharField(choices=[('push', 'Push'), ('sms', 'SMS'), ('in_app', 'В приложении'), ('log', 'Лог')], default='in_app', max_length=32, verbose_name='Канал'),
        ),
        migrations.AlterField(
            model_name='notificationevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='notificationevent',
            name='event_type',
            field=models.CharField(max_length=80, verbose_name='Тип события'),
        ),
        migrations.AlterField(
            model_name='notificationevent',
            name='payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Доп. данные'),
        ),
        migrations.AlterField(
            model_name='notificationevent',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отправлено'),
        ),
        migrations.AlterField(
            model_name='notificationevent',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('sent', 'Отправлено'), ('failed', 'Ошибка'), ('skipped', 'Пропущено')], default='pending', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='notificationevent',
            name='title',
            field=models.CharField(max_length=180, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='notificationevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
