# Generated by Django 5.2.17 on 2026-09-14 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('orders', '0006_alter_order_cancellation_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='chatroom',
            options={'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='attachment_url',
            field=models.URLField(blank=True, verbose_name='Вложение'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Отправлено'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='kind',
            field=models.CharField(choices=[('text', 'Текст'), ('photo', 'Фото'), ('video', 'Видео'), ('price_proposal', 'Предложение цены'), ('system', 'Системное')], default='text', max_length=32, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='price_uzs',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена, UZS'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Прочитано'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom', verbose_name='Чат'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Закрыт'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='orders.order', verbose_name='Заказ'),
        ),
    ]
